nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-rescript.cjs
    spec: "https://github.com/reason-seoul/yarn-plugin-rescript/releases/download/v0.0.0-da87589/plugin-rescript.js"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
