// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as React$1 from "@nanostores/react";
import * as NanoTodoListStore from "@todomvc-core/nanoTodoListStore";

function useNanoTodoList(param) {
  var todoList = React$1.useStore(NanoTodoListStore.todoListStore);
  return {
          todoList: todoList
        };
}

function useNanoActions(param) {
  return NanoTodoListStore.actions;
}

async function nanostoreInit(init) {
  NanoTodoListStore.todoListStore.set(init);
}

function make(children) {
  return React.createElement("div", undefined, children);
}

var NanoTodoListWrapper = {
  make: make
};

export {
  useNanoTodoList ,
  useNanoActions ,
  nanostoreInit ,
  NanoTodoListWrapper ,
}
/* react Not a pure module */
