// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@nanostores/react";
import * as NanoTodoListStore from "@todomvc-core/nanoTodoListStore";

function useNanoTodoList(param) {
  var todoList = React.useStore(NanoTodoListStore.todoListStore);
  return {
          todoList: todoList
        };
}

function useNanoActions(param) {
  return NanoTodoListStore.actions;
}

async function nanostoreInit(init) {
  NanoTodoListStore.todoListStore.set(init);
}

export {
  useNanoTodoList ,
  useNanoActions ,
  nanostoreInit ,
}
/* @nanostores/react Not a pure module */
