// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TodoEditingForm from "./TodoEditingForm.bs.js";
import * as TodoDeleteButton from "./TodoDeleteButton.bs.js";
import * as TodoCompleteCheckbox from "./TodoCompleteCheckbox.bs.js";

function TodoListItem(props) {
  var todo = props.todo;
  return React.createElement("li", undefined, React.createElement(TodoEditingForm.make, {
                  todo: todo
                }), React.createElement(TodoCompleteCheckbox.make, {
                  id: todo.id,
                  isCompleted: todo.isCompleted
                }), React.createElement(TodoDeleteButton.make, {
                  todoId: todo.id
                }));
}

var make = TodoListItem;

export {
  make ,
}
/* react Not a pure module */
