// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

var testTodo = {
  id: 1,
  content: "test",
  isCompleted: false
};

var init = {
  todoList: [testTodo]
};

var context = React.createContext(function (param) {
      return init;
    });

var make = context.Provider;

var Provider = {
  make: make
};

var UseTodoListContext = {
  testTodo: testTodo,
  init: init,
  context: context,
  Provider: Provider
};

function fakeActions_addTodo(content) {
  console.log(content);
}

function fakeActions_completeTodo(id, isCompleted) {
  console.log(id, isCompleted);
}

function fakeActions_deleteTodo(id) {
  console.log(id);
}

function fakeActions_changeTodo(id, newContent) {
  console.log(id, newContent);
}

var fakeActions = {
  addTodo: fakeActions_addTodo,
  completeTodo: fakeActions_completeTodo,
  deleteTodo: fakeActions_deleteTodo,
  changeTodo: fakeActions_changeTodo
};

var context$1 = React.createContext(function (param) {
      return fakeActions;
    });

var make$1 = context$1.Provider;

var Provider$1 = {
  make: make$1
};

var UseTodoActionsContext = {
  fakeActions: fakeActions,
  context: context$1,
  Provider: Provider$1
};

function useTodoActions(param) {
  return Curry._1(React.useContext(context$1), undefined);
}

export {
  UseTodoListContext ,
  UseTodoActionsContext ,
  useTodoActions ,
}
/* context Not a pure module */
