// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as TodoContext from "./TodoContext.bs.js";

function TodoEditingForm(props) {
  var todo = props.todo;
  var todoActions = TodoContext.useTodoActions(undefined);
  var match = React.useState(function () {
        return false;
      });
  var setIsEditing = match[1];
  var isEditing = match[0];
  var editRef = React.useRef(null);
  var match$1 = React.useState(function () {
        return todo.content;
      });
  var setText = match$1[1];
  var text = match$1[0];
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    Curry._1(setText, (function (_prev) {
            return value;
          }));
  };
  React.useEffect((function () {
          var dom = editRef.current;
          if (!(dom == null)) {
            dom.focus();
          }
          
        }), [isEditing]);
  var startEdit = function (_e) {
    Curry._1(setIsEditing, (function (param) {
            return true;
          }));
  };
  var endEdit = function (_e) {
    Curry._1(setIsEditing, (function (param) {
            return false;
          }));
    todoActions.changeTodo(todo.id, text);
  };
  if (isEditing) {
    return React.createElement(React.Fragment, undefined, React.createElement("input", {
                    ref: Caml_option.some(editRef),
                    placeholder: todo.content,
                    type: "text",
                    value: text,
                    onChange: onChange
                  }), React.createElement("button", {
                    "aria-label": "할일을 " + todo.content + "에서 " + text + "로 수정하시려면 클릭하세요.",
                    type: "button",
                    onClick: endEdit
                  }, "완료"));
  } else {
    return React.createElement(React.Fragment, undefined, todo.content, React.createElement("button", {
                    "aria-label": "할일 " + todo.content + "을 수정하시려면 클릭하세요.",
                    type: "button",
                    onClick: startEdit
                  }, "수정"));
  }
}

var make = TodoEditingForm;

export {
  make ,
}
/* react Not a pure module */
