// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TodoContext from "./TodoContext.bs.js";

function TodoCompleteCheckbox(props) {
  var id = props.id;
  var todoActions = TodoContext.useTodoActions(undefined);
  var onChange = function ($$event) {
    var isCompleted = $$event.target.checked;
    todoActions.completeTodo(id, isCompleted);
  };
  var onKeyUp = function ($$event) {
    if ($$event.key !== "Space") {
      return ;
    }
    var isCompleted = $$event.target.checked;
    todoActions.completeTodo(id, !isCompleted);
  };
  return React.createElement("input", {
              "aria-label": "완료",
              checked: props.isCompleted,
              type: "checkbox",
              onKeyUp: onKeyUp,
              onChange: onChange
            });
}

var make = TodoCompleteCheckbox;

export {
  make ,
}
/* react Not a pure module */
