// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as TodoContext from "./TodoContext.bs.js";
import * as NanoTodoList from "./NanoTodoList.bs.js";

function make(param) {
  return React.createElement(TodoContext.UseTodoListContext.Provider.make, {
              value: NanoTodoList.useNanoTodoList,
              children: React.createElement(TodoContext.UseTodoActionsContext.Provider.make, {
                    value: NanoTodoList.useNanoActions,
                    children: React.createElement(App.make, {})
                  })
            });
}

export {
  make ,
}
/* App Not a pure module */
