// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as TodoContext from "./TodoContext.bs.js";

function TodoForm(props) {
  var todoActions = TodoContext.useTodoActions(undefined);
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    Curry._1(setText, (function (_prev) {
            return value;
          }));
  };
  var onSubmit = function ($$event) {
    $$event.preventDefault();
    todoActions.addTodo(text);
  };
  return React.createElement("form", {
              onSubmit: onSubmit
            }, React.createElement("label", undefined, "새로운 할일", React.createElement("input", {
                      type: "text",
                      onChange: onChange
                    })));
}

var make = TodoForm;

export {
  make ,
}
/* react Not a pure module */
