// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as TodoContext from "./TodoContext.bs.js";
import * as TodoListItem from "./TodoListItem.bs.js";
import * as JsxPPXReactSupport from "rescript/lib/es6/jsxPPXReactSupport.js";

function TodoList(props) {
  var match = Curry._1(React.useContext(TodoContext.UseTodoListContext.context), undefined);
  return React.createElement("ul", {
              className: "flex flex-col gap-2 m-2"
            }, Belt_Array.map(match.todoList, (function (todo) {
                    return JsxPPXReactSupport.createElementWithKey(String(todo.id), TodoListItem.make, {
                                todo: todo
                              });
                  })));
}

var make = TodoList;

export {
  make ,
}
/* react Not a pure module */
