// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(props) {
  return React.createElement("button", undefined, "Hello World");
}

var make = Button;

export {
  make ,
}
/* react Not a pure module */
