// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Runner from "./Runner.bs.js";
import * as NanoTodoList from "../src/NanoTodoList.bs.js";

Runner.runReactImpl("nanostore", NanoTodoList.useNanoTodoList, NanoTodoList.useNanoActions, NanoTodoList.NanoTodoListWrapper.make, NanoTodoList.nanostoreInit);

export {
  
}
/*  Not a pure module */
