// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Runner from "./Runner.bs.js";
import * as ReduxTodoList from "../src/ReduxTodoList.bs.js";
import * as UseReduxTodoList from "@todomvc-react/hooks/useReduxTodoList";

Runner.runReactImpl("nanostore", (function (prim) {
        return UseReduxTodoList.useReduxTodoList();
      }), (function (prim) {
        return UseReduxTodoList.useReduxActions();
      }), ReduxTodoList.ReduxWrapper.make, (function (prim) {
        return UseReduxTodoList.reduxInit(prim);
      }));

export {
  
}
/*  Not a pure module */
