// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "../src/App.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as TodoContext from "../src/TodoContext.bs.js";
import RunTest from "../../test/runTest";
import * as ReactTestingLibrary from "@rescriptbr/react-testing-library/src/ReactTestingLibrary.bs.js";
import * as SharedContainer from "@todomvc-core/sharedContainer";

function runTest(prim) {
  RunTest(prim);
}

function runReactImpl(name, useTodoListImpl, useTodoActionsImpl, make, setup) {
  RunTest({
        framework: "react-rescript: " + name + "",
        render: (async function (init) {
            SharedContainer.inject("storage").set("todo-list", init);
            await Curry._1(setup, init);
            return ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, React.createElement(TodoContext.make, {
                            useTodoListImpl: useTodoListImpl,
                            useTodoActionsImpl: useTodoActionsImpl,
                            children: Curry._1(make, React.createElement(App.make, {}))
                          }));
          })
      });
}

export {
  runTest ,
  runReactImpl ,
}
/* App Not a pure module */
